---
sudo: false
language: ruby
cache: bundler
dist: focal
script: 'bundle exec rake test'
bundler_args: --without release
rvm:
  - 2.5
  - 2.6
  - 2.7
notifications:
  email: false
  irc:
    on_success: always
    on_failure: always
    channels:
      - "chat.freenode.org#voxpupuli-notifications"
deploy:
  provider: rubygems
  api_key:
    secure: "Tbf1EbLEobIIox+fftJZADZsfQQ6kl0urcMNetK7NJzFo/negD/WyJIUj3kro/B7buyYADEjTui/JR4o8EPbugfM3ie5vYOd5k3AesSzbdr4BSwGe/cGbGOB7/PZuGfFLkb94/FiCU2mIwibkbh1rHWGlBoPj7ntL0+5ZtdvsM4="
  gem: modulesync
  on:
    rvm: 2.7
    tags: true
    all_branches: true
    repo: voxpupuli/modulesync
